### ISSUE TITLE
Uncaught TypeError: jade.attr is not a function

### ISSUE THREAD

**Issue by skolsuper** [mogelbrod/apply-loader#1]
```
@Component({
  selector: '#landing-page',
  template: require('jade!./landing-page.component.jade')(),
  styles: ['* { display: block; }', 'a { color: white }']
})
export class LandingPage {}
```

I had the above code which worked.  I tried using the apply loader by substituting the template line with this:

```
  template: require('apply!jade!./landing-page.component.jade'),
```

It works on first compile but if I change the jade template, webpack recompiles but the angular app fails to bootstrap on reload, throwing the error in the title.

**Comment by mogelbrod** [comment]
I haven't used this plugin since it was written and therefore have not experienced any problems with it, unfortunately.

Have you tried an earlier jade release?
The only thing in this module I can think of that might be causing the above error is setting the [cacheable flag](https://github.com/mogelbrod/apply-loader/blob/master/index.js#L7). Try removing that line and see if anything changes.

**Comment by skolsuper** [comment]
Sorry, I forgot about this issue.  I never got to the bottom of it, but I'm pretty sure it was not a problem with this package.  Unfortunately, my fix was to stop using jade :(
